name: main-job
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    name: Github Actions kata
    steps:
      - name: Clone-down
        uses: actions/checkout@v3   
      - name: build
        run: ci/build-app.sh
      - name: test
        run: ci/unit-test-app.sh